name: vitkart
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http:
  shared_preferences: 
  jwt_decoder:
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.1
  smooth_page_indicator: ^1.1.0
  loading_animation_widget: ^1.2.0+4
  cherry_toast: ^1.6.4
  
  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  pinput: ^3.0.1
  iconify: ^0.0.1
  iconify_flutter: ^0.0.5
  cupertino_date_textbox: ^1.0.3
  drop_down_list: ^0.0.6
  timer_count_down: ^2.2.2
  fade_shimmer: ^2.2.0
  animated_segmented_tab_control: ^1.2.0
  dotted_border: ^2.1.0
  path_provider: ^2.1.1
  image_picker: ^1.0.5
  image_cropper: ^5.0.1
  flutter_launcher_icons: 
  permission_handler: ^11.0.1
  razorpay_flutter: ^1.3.5
  pull_down_button: ^0.9.3

  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0


flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icons/vitkart/vitkart_logogreen.png"
  image_path_android: "assets/icons/vitkart/vitkart_logogreen.png"
  image_path: "assets/icons/vitkart/vitkart_logogreen.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/images/products/biscuit.png
    - assets/icons/categories/
    - assets/icons/events/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/content/back.png
    - assets/icons/vitkart/
    - assets/images/on_boarding_images/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800